[project]
name = "s3-upload-server"
version = "0.1.0"
description = "MCP server for uploading files to S3 with public access"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.6.0",
    "boto3>=1.34.0",
]
